### ISSUE TITLE
Error 500 when view issue with subtasks (only conflicts with plugin issue_tab or default_custom_query)

### ISSUE THREAD

**Issue by msneet** [SMS-IT/redmine_subtask_list_columns#8]
Plugin work in clear Redmine 3.2.0 without any plugins. But when installing plugin "redmine_issue_tabs" (https://github.com/pineapplethief/redmine_issue_tabs) or "redmine_default_custom_query" (https://github.com/hidakatsuya/redmine_default_custom_query) error raises.

```
undefined method `get_fields_for_project' for #<#<Class:0x007f499e2a6068>:0x007f499ee8aff0> 
```

```

/opt/bitnami/apps/redmine/htdocs/plugins/subtask_list_columns/lib/subtask_list_columns_lib.rb:19:in `render_descendants_tree_with_listed'
/opt/bitnami/apps/redmine/htdocs/app/views/issues/show.html.erb:101:in `_1844222ca40118bb101ee18c37dac10c'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/template.rb:145:in `block in render'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/template.rb:333:in `instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/template.rb:143:in `render'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/deface-1.0.2/lib/deface/action_view_extensions.rb:41:in `render'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/renderer/template_renderer.rb:14:in `render'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/renderer/renderer.rb:42:in `render_template'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/renderer/renderer.rb:23:in `render'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/rendering.rb:100:in `_render_template'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/rendering.rb:83:in `render_to_body'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/abstract_controller/rendering.rb:25:in `render'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/rendering.rb:16:in `render'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/opt/bitnami/ruby/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:43:in `render'
/opt/bitnami/apps/redmine/htdocs/app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/mime_responds.rb:217:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
/opt/bitnami/apps/redmine/htdocs/app/controllers/issues_controller.rb:115:in `show'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:198:in `process_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/rendering.rb:10:in `process_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:313:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:312:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:312:in `block in halting'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `block in around'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/rescue.rb:29:in `process_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:137:in `process'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.5/lib/action_view/rendering.rb:30:in `process'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal.rb:196:in `dispatch'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_controller/metal.rb:237:in `block in action'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:76:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:45:in `serve'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `serve'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:817:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/flash.rb:260:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/query_cache.rb:36:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `public_send'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `method_missing'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.6/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

```

**Comment by msneet** [comment]
```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Git                            2.6.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.1.2
  computed_custom_field          0.0.6
  redmine_base_deface            0.0.1
  redmine_custom_values_projects 0.0.1
  redmine_custom_workflows       0.1.6
  redmine_edit_custom_fields     0.0.2
  redmine_edit_issue_author      0.0.1
  redmine_group_owners           2.0.0
  redmine_hours                  0.1.2
  redmine_issue_tabs             1.1.1
  redmine_lightbox2              0.2.5
  redmine_local_avatars          0.2.0
  redmine_login_audit            0.3.1
  redmine_maintenance_mode       2.0.1
  redmine_pivot_table            0.0.3
  subtask_list_columns           0.0.3
  tracker_hider                  0.0.1
  unread_issues                  2.0.0
  usability                      2.1.0
```

**Comment by Cybermoon12** [comment]
Same problem here with issue_tabs 1.1.1 :-(

FYI : this fork works for me : http://www.redmine.org/plugins/subtaskcolumns

**Comment by smoolya17** [comment]
i installed the plugin. The plugin is visible in administration settings as Subtask list columns but when i try to open the configured issue with issue columns of subtasks it shows internal error

**Comment by smoolya17** [comment]
it seems the plugin  shows error when i use it alongwith ERPmine plugin

**Comment by lilyroselily** [comment]
+1 the same error
