### ISSUE TITLE
It's not working on 3.1 version

### ISSUE THREAD

**Issue by marcosantos** [SMS-IT/redmine_subtask_list_columns#2]
I already have installed your plugin on Debian's virtual machine, but its not working. Migration occurred as expected, but when I was relaunched I can't see Subtask list menu.

**Comment by redkozubov** [comment]
It's strange. Could you attach yout redmine logs ?

**Comment by lublasco** [comment]
Same here with 3.1. and a Bitnami installation. Error follows when trying to see parent task.

Production log shows following:

Started GET "/issues/1" for 46.26.72.199 at 2015-11-04 12:30:05 +0000
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"1"}
  Current user: user (id=1)
  Rendered issues/_action_menu.html.erb (2.8ms)
  Rendered plugins/redmine_contacts/app/views/deals_issues/_show.html.erb (0.7ms)
  Rendered issues/show.html.erb within layouts/base (203.4ms)
Completed 500 Internal Server Error in 242ms (ActiveRecord: 4.5ms)

ActionView::Template::Error (undefined method `get_fields_for_project' for #<#<Class:0x007f293d6839a0>:0x007f293df73b28>):
     98:   <%= link_to_new_subtask(@issue) if User.current.allowed_to?(:manage_subtasks, @project) %>
     99: </div>
    100: <p><strong><%=l(:label_subtask_plural)%></strong></p>
    101: <%= render_descendants_tree(@issue) unless @issue.leaf? %>
    102: </div>
    103: <% end %>
    104: 
  app/views/issues/show.html.erb:101:in`_app_views_issues_show_html_erb___3666606263139148506_69907783297820'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in`show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Thanks in advance for your help!

**Comment by redkozubov** [comment]
Dear, lublasco.
I downloaded Bitnami Redmine 3.1.1-1 (from the site : https://bitnami.com/stack/redmine/installer) and install on it only our plugin. It works without errors.
Logs also contains no information about errors. 

Do you use any other plugins? 
Could you send your plugin list with versions?

**Comment by lublasco** [comment]
Hi, I have uninstalled all plugins and the problem remains. Log shows the same messages.

My installation:
Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.0.0-p647 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Cvs                            1.12.13
  Git                            1.9.5
  Filesystem  
Redmine plugins:
  subtask_list_columns           0.0.2

Thanks.

**Comment by redkozubov** [comment]
Dear, lublasco.
Try to replace the files in the folder plugins / subtask list_columns on files from the archive:
https://drive.google.com/file/d/0B0huExhfmJztZ0hVZDFUNUxTTTQ/view?usp=sharing

**Comment by lublasco** [comment]
Rake gives an error and bundle is aborted:

rake aborted!
LoadError: No such file to load -- subtask_list_columns_lib
/opt/bitnami/apps/redmine/htdocs/plugins/subtask_list_columns/init.rb:3:in `<top                (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in`block in load'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in`load'
/opt/bitnami/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in `<top (               required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in`<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by redkozubov** [comment]
Dear, lublasco.
I'm sorry, I forgot to add a file that was changed.
Please, try again:
https://drive.google.com/file/d/0B0huExhfmJztMVZ5QjJTcnJCd0E/view?usp=sharing

**Comment by lublasco** [comment]
OK, now I see. The plugin works correctly if you haven't defined any custom field. As soon as you create a custom field for the parent task (list, text or any other kind) you get an error when trying to visit the parent task.

Started GET "/issues/11" for 46.26.72.199 at 2015-11-10 09:21:50 +0000
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"11"}
  Current user: user (id=1)
  Rendered issues/_action_menu.html.erb (2.5ms)
  Rendered issues/show.html.erb within layouts/base (17.8ms)
Completed 500 Internal Server Error in 47ms (ActiveRecord: 3.4ms)

ActionView::Template::Error (undefined method `listed?' for #<IssueCustomField:0x007fdc760a8cf0>):
     98:   <%= link_to_new_subtask(@issue) if User.current.allowed_to?(:manage_subtasks, @project) %>
     99: </div>
    100: <p><strong><%=l(:label_subtask_plural)%></strong></p>
    101: <%= render_descendants_tree(@issue) unless @issue.leaf? %>
    102: </div>
    103: <% end %>
    104: 
  app/helpers/issues_helper.rb:30:in`block in issue_list'
  app/helpers/issues_helper.rb:26:in `each'
  app/helpers/issues_helper.rb:26:in`issue_list'
  app/views/issues/show.html.erb:101:in `_app_views_issues_show_html_erb__3764878012480136181_70292417097640'
  app/controllers/issues_controller.rb:118:in`block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in`sudo_mode'

**Comment by redkozubov** [comment]
Dear, lublasco.
We found a mistake, corrected it and uploaded a new version of the plugin. 
Thank you for the feedback!

**Comment by lublasco** [comment]
Great! Now the plugin is working perfectly!
Thank you very much for your work!

**Comment by skurtzemann** [comment]
I've got the problem error with the corrected version of the plugin

```
Started GET "/issues/1" for 62.241.121.127 at 2015-11-16 09:09:26 +0000
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"1"}
  Current user: admin (id=1)
  Rendered issues/_action_menu.html.erb (4.4ms)
  Rendered plugins/redmine_checklists/app/views/checklists/_checklist_item.html.erb (1.1ms)
  Rendered plugins/redmine_checklists/app/views/issues/_checklist.html.erb (4.4ms)
  Rendered issues/show.html.erb within layouts/base (82.8ms)
Completed 500 Internal Server Error in 138ms (ActiveRecord: 7.1ms)

ActionView::Template::Error (undefined method `get_fields_for_project' for #<#<Class:0x00000008aed898>:0x00000008010920>):
     98:   <%= link_to_new_subtask(@issue) if User.current.allowed_to?(:manage_subtasks, @project) %>
     99: </div>
    100: <p><strong><%=l(:label_subtask_plural)%></strong></p>
    101: <%= render_descendants_tree(@issue) unless @issue.leaf? %>
    102: </div>
    103: <% end %>
    104:
  app/views/issues/show.html.erb:101:in `_app_views_issues_show_html_erb__2940984214966853437_72907300'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Here the redmine version and plugins I used:

```
Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [x86_64-linux-gnu]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.6.2
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.3
  redmine_ckeditor               1.1.2
  redmine_issue_templates        0.1.1
  redmine_stats                  0.0.3
  subtask_list_columns           0.0.1
  timelog_timer                  2.0.0
```

Thanks

**Comment by redkozubov** [comment]
Dear, skurtzemann. 
Apparently you are using an older version of the plugin. I see that you have a version 0.0.1. We repaired the bug in version 0.0.3, use it

**Comment by skurtzemann** [comment]
Hello redkozubov,
I've the same problem when I use the version 0.0.3 (commit 6878fb2c7e428e6a27f55636a07de947119f28c7)
