### ISSUE TITLE
parent or subtask issues can't view(undefined method `get_fields_for_project')

### ISSUE THREAD

**Issue by kskyj** [SMS-IT/redmine_subtask_list_columns#5]
Hi. This is very good plugin.
I’m getting an error.
My redmine version is v3.2(from 2.3.1 migration) and plugin version is v0.0.3
I  clicked parent or subtask issues and then get error message

Error message below:
Started GET "/issues/28" for 127.0.0.1 at 2016-01-19 10:53:11 +0900
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"28"}
  Current user: kskyj (id=3)
  Rendered issues/_action_menu.html.erb (6.0ms)
  Rendered plugins/redmine_checklists/app/views/issues/_checklist.html.erb (1.3ms)
  Rendered issues/show.html.erb within layouts/base (232.8ms)
Completed 500 Internal Server Error in 315ms (ActiveRecord: 22.7ms)

ActionView::Template::Error (undefined method `get_fields_for_project' for #<#<Class:0x0000000b4fcfa8>:0x0000000aa77538>):
     98:   <%= link_to_new_subtask(@issue) if User.current.allowed_to?(:manage_subtasks, @project) %>
     99: </div>
    100: <p><strong><%=l(:label_subtask_plural)%></strong></p>
    101: <%= render_descendants_tree(@issue) unless @issue.leaf? %>
    102: </div>
    103: <% end %>
    104: 
  plugins/subtask_list_columns/lib/subtask_list_columns_lib.rb:19:in`render_descendants_tree_with_listed'
  app/views/issues/show.html.erb:101:in `_app_views_issues_show_html_erb___1664568814319490996_79352240'
  app/controllers/issues_controller.rb:118:in`block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in`sudo_mode'

Please help me.

**Comment by LeviticusMB** [comment]
Me too. I'd really like to be able to use this plugin.

**Comment by projectplant** [comment]
Me, too. Redmine 3.2, Plugin 0.0.3.

**Comment by kskyj** [comment]
I used another plugin, a forked of Subtask_list_columns. Refer to http://www.redmine.org/plugins/subtaskcolumns
It works with redmine v3.2.

**Comment by SithLordRevan** [comment]
Hi,

I solved the problem. It is necessary to add the alias definition method into file "lib/subtask_list_columns_lib.rb".

```
 def self.included(base)
        base.send(:include, InstanceMethods)
        base.class_eval do
            unloadable

            alias_method_chain :render_descendants_tree, :listed
            alias_method :get_fields_for_project, :get_fields_for_project
            alias_method :remove_unavailable_custom_fields, :remove_unavailable_custom_fields
            alias_method :get_first_column_in_table, :get_first_column_in_table
            alias_method :get_td, :get_td
      end
    end
```
